Telcel.R9.Estructura.Presentacion/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Telcel.R9.Estructura.Presentacion.Controllers
{
    public class EmpleadoController : Controller
    {
        [HttpGet]
        public ActionResult EmpleadoBuscar()
        {
            Telcel.R9.Estructura.Negocio.Empleado empleado = new Telcel.R9.Estructura.Negocio.Empleado();
            empleado.Puesto = new Negocio.Puesto();
            empleado.Departamento = new Negocio.Departamento();
            empleado.Empleados = new List<Object>();

            Telcel.R9.Estructura.Negocio.Result result = Telcel.R9.Estructura.Negocio.Empleado.GetAll();

            if (result.Correct)
            {
                empleado.Empleados = result.Objects;
            }
            else
            {
                ViewBag.Message = result.ErrorMessage;
            }
            return View(empleado);
        }

        [HttpPost]
        public ActionResult EmpleadoBuscar(string Nombre)
        {
            Telcel.R9.Estructura.Negocio.Empleado empleado = new Telcel.R9.Estructura.Negocio.Empleado();
            empleado.Puesto = new Negocio.Puesto();
            empleado.Departamento = new Negocio.Departamento();
            empleado.Empleados = new List<Object>();

            Telcel.R9.Estructura.Negocio.Result result = Telcel.R9.Estructura.Negocio.Empleado.GetAll(Nombre);

            if (result.Correct)
            {
                empleado.Empleados = result.Objects;
            }
            else
            {
                ViewBag.Message = result.ErrorMessage;
            }
            return View(empleado);
        }

        [HttpGet]
        public ActionResult EmpleadoEliminar(int EmpleadoID)
        {
            Telcel.R9.Estructura.Negocio.Result result = Telcel.R9.Estructura.Negocio.Empleado.Delete(EmpleadoID);
            if (result.Correct)
            {
                ViewBag.Message = "Se elimino Correctamente el empleado";
            }
            else
            {
                ViewBag.Message = "Ocurrio un problema al eliminar. Error: " + result.ErrorMessage;
            }
            return PartialView("Modal");
        }

        [HttpGet]
        public ActionResult CargaMasiva()
        {
            Telcel.R9.Estructura.Negocio.Empleado empleado = new Telcel.R9.Estructura.Negocio.Empleado();
            return View(empleado);
        }

        [HttpPost]
        public ActionResult CargaMasiva(Telcel.R9.Estructura.Negocio.Empleado empleado, HttpPostedFileBase txtEmpleado)
        {
            if (Session["ListEmpleados"] == null)
            {
                if (txtEmpleado == null)
                {
                    ViewBag.Message = "No se selecciono un archivo";
                    return PartialView("Modal");
                }
                else
                {
                    string extension = Path.GetExtension(txtEmpleado.FileName);
                    if (extension == ".txt")
                    {
                        var fecha = DateTime.Now.ToString("dd-MM-yyyy HHmmss");
                        string direccionTxt = Server.MapPath("~/CargaMasiva/TXT/" + Path.GetFileNameWithoutExtension(txtEmpleado.FileName) + "-" + fecha + ".txt");
                        txtEmpleado.SaveAs(direccionTxt);

                        empleado = Previsualizar(empleado, txtEmpleado);

                        Session["ListEmpleados"] = empleado.Empleados;
                    }
                    else
                    {
                        ViewBag.Message = "Archivo no valido";
                        return PartialView("Modal");
                    }
                }
            }
            else
            {
                if (txtEmpleado != null)
                {
                    Session["ListEmpleados"] = null;
                    CargaMasiva(empleado, txtEmpleado);
                }
                else
                {
                    var x = (List<object>)Session["ListEmpleados"];
                    empleado.Empleados = x;

                    CargarDatos(empleado);

                    Session["ListEmpleados"] = null;

                    ViewBag.Message = "Se han insertado los registros";
                    return PartialView("Modal");

                }
            }
            return View(empleado);
        }
        //TXT
        public static Telcel.R9.Estructura.Negocio.Empleado Previsualizar(Telcel.R9.Estructura.Negocio.Empleado empleado, HttpPostedFileBase txtEmpleado)
        {
            empleado.Empleados = new List<object>();
            using (StreamReader file = new StreamReader(txtEmpleado.InputStream, System.Text.Encoding.Default))
            {
                int counter = 0;
                string ln;

                while ((ln = file.ReadLine()) != null)
                {
                    if (counter > 0)
                    {
                        var datos = ln.Split(',');

                        Telcel.R9.Estructura.Negocio.Empleado empleadoItem = new Negocio.Empleado();
                        empleadoItem.Puesto = new Negocio.Puesto();
                        empleadoItem.Departamento = new Negocio.Departamento();

                        empleadoItem.Nombre = datos[0];
                        empleadoItem.Departamento.DepartamentoID = (datos[1] != null) ? int.Parse(datos[1]) : int.Parse("0");
                        empleadoItem.Puesto.PuestoID = (datos[2] != null) ? int.Parse(datos[2]) : int.Parse("0");

                        empleado.Empleados.Add(empleadoItem);
                    }
                    counter++;
                }
            }
            return empleado;
        }
        public void CargarDatos(Telcel.R9.Estructura.Negocio.Empleado empleado)
        {
            List<string> list = new List<string>();
            int counter = 1;
            foreach (Telcel.R9.Estructura.Negocio.Empleado empleadoItem in empleado.Empleados)
            {
                Telcel.R9.Estructura.Negocio.Result result = Telcel.R9.Estructura.Negocio.Empleado.Add(empleadoItem);

                if (result.Correct)
                {
                    list.Add("La insersion del empleado: " + empleadoItem.Nombre + " fue exitosa.");
                }
                else
                {
                    list.Add("Hubo un error al insertar el empleado: " + empleadoItem.Nombre + " Error: ." + result.ErrorMessage);
                }
                counter++;
            }

            var fecha = DateTime.Now.ToString("dd-MM-yyyy HHmmss");
            string path = Server.MapPath("~/CargaMasiva/Reportes/" + "CargaMasiva_" + fecha + ".txt");

            using (StreamWriter archivo = System.IO.File.CreateText(path))
            {
                foreach (string msj in list)
                {
                    archivo.WriteLine(msj);
                }
            }
        }
    }
}

Telcel.R9.Estructura.Presentacion/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Telcel.R9.Estructura.Presentacion.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Telcel.R9.Estructura.Presentacion/Views/Empleado/CargaMasiva.cshtml
@model Telcel.R9.Estructura.Negocio.Empleado
@{
    ViewBag.Title = "CargaMasiva";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Carga Masiva</h2>
            <hr>
        </div>
    </div>

    @using (Html.BeginForm("CargaMasiva", "Empleado", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row margen">
            <div class="col-md-9 text-center">
                <input type="file" name="txtEmpleado">
                @Html.HiddenFor(model => model.Empleados)
            </div>

            @if (Model.Empleados == null)
            {
                <div class="col-md-3 text-center">
                    <div class="btn-group">
                        <button type="submit" class="btn btn-info">Visualizar</button>
                        @Html.ActionLink("Regresar", "EmpleadoBuscar", "Empleado", new { @class = "btn btn-danger" })
                    </div>
                </div>
            }
            else
            {
                <div class="col-md-pull-1 pull-right text-center">
                    <div class="btn-group">
                        <button type="submit" class="btn btn-success">Cargar</button>
                    </div>
                </div>
            }
        </div>
    }
    @if (Model.Empleados != null)
    {
        <div class="table-responsive">
            <table class="table table-striped table-hover text-center text-nowrap">
                <thead>
                    <tr>
                        <th class="text-center">Nombre</th>
                        <th class="text-center">Puesto ID</th>
                        <th class="text-center">Departamento ID</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Telcel.R9.Estructura.Negocio.Empleado empleado in Model.Empleados)
                    {
                        <tr>
                            <td>@empleado.Nombre</td>
                            <td>@empleado.Puesto.PuestoID</td>
                            <td>@empleado.Departamento.DepartamentoID</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
</div>

Telcel.R9.Estructura.Presentacion/Views/Empleado/EmpleadoBuscar.cshtml
@model Telcel.R9.Estructura.Negocio.Empleado
@{
    ViewBag.Title = "EmpleadoBuscar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Empleado</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p>Selecciona un empleado que desees eliminar</p>
        </div>
    </div>
    @*<div class="row">
            <div class="col-md-12">
                <div class="btn-group">
                    @Html.ActionLink("CargaMasiva", "CargaMasiva", "Empleado", new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>*@
    <hr>
    <div class="row">
        @using (Html.BeginForm("EmpleadoBuscar", "Empleado", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="col-md-9">
                <div class="form-group">
                    @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @placeholder = "Nombre del Empleado" })
                </div>
            </div>
            <div class="col-md-3 pull-right">
                <div class="btn-group">
                    @Html.ActionLink("CargaMasiva", "CargaMasiva", "Empleado", new { @class = "btn btn-danger" })
                    <button type="submit" class="btn btn-success">Buscar</button>
                </div>
            </div>
        }
    </div>

    @if (Model.Empleados.Count != 0)
    {
        <div class="table-responsive">
            <table class="table table-striped table-hover text-center text-nowrap">
                <thead>
                    <tr>
                        <th class="text-center">Empleado ID</th>
                        <th class="text-center">Nombre</th>
                        <th class="text-center">Puesto ID</th>
                        <th class="text-center">Descripcion Puesto</th>
                        <th class="text-center">Departamento ID</th>
                        <th class="text-center">Descripcion Puesto</th>
                        <th class="text-center">Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Telcel.R9.Estructura.Negocio.Empleado empleado in Model.Empleados)
                    {
                        <tr>
                            <td>@empleado.EmpleadoID</td>
                            <td>@empleado.Nombre</td>
                            <td>@empleado.Puesto.PuestoID</td>
                            <td>@empleado.Puesto.Descripcion</td>
                            <td>@empleado.Departamento.DepartamentoID</td>
                            <td>@empleado.Departamento.Descripcion</td>
                            <td>
                                <a class="btn btn-danger" href="@Url.Action("EmpleadoEliminar", "Empleado", new {EmpleadoID = empleado.EmpleadoID})" onclick="return confirm('¿Estas seguro de eliminar el Empleado');">
                                    <i class="far fa-trash-alt"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    else
    {
        <div class="alert alert-danger" role="alert">
            <p>No se encontraron empleados registrados</p>
        </div>
    }
</div>

Telcel.R9.Estructura.Presentacion/Views/Empleado/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


<div class="modal fade" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Aviso</h4>
            </div>
            <div class="modal-body">
                <p>@ViewBag.Message</p>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "EmpleadoBuscar", "Empleado", new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal('show');
</script>

Telcel.R9.Estructura.Presentacion/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Telcel.R9.Estructura.Presentacion/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Telcel.R9.Estructura.Presentacion/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Telcel.R9.Estructura.Presentacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Empleado", "EmpleadoBuscar", "Empleado")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>